version: 0.2

env:
  variables:
    EXPO_USERNAME: marcski55

phases:
  install:
    runetime-versions:
      nodejs: 14.x
    commands:
      - echo Installing global dependencies...
      - npm install --global expo-cli sharp-cli
      - export EXPO_CLI_PASSWORD=$(aws ssm get-parameter --name "expo-cli-password" --region "us-east-2" --query 'Parameter.Value' --with-decryption --output text)
      - npx expo login --non-interactive -u ${EXPO_USERNAME}
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --legacy-peer-deps
      - echo Congifuring Android Build...
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the actual code
      - expo publish
      - expo build:web
      - expo build:android -t apk --no-wait
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Android build status can be checked at https://expo.dev/
artifacts:
  files:
    - web-build/**/*
